version: "3"
services:
  backend:
    build: ../server
    deploy:
      replicas: 3
    networks:
      - loadbalancing

  nginx:
    build: ../nginx
    ports:
      - "4000:4000"
    networks:
      - loadbalancing
    depends_on:
      - backend

networks:
  loadbalancing:
