version: "3"
services:
  backend:
    build: ../server
    deploy:
      replicas: 4
    environment:
      - CONTAINER_NAME=backend_${i}
    networks:
      - loadbalancing

  nginx:
    build: ../nginx
    ports:
      - "4000:4000"
    networks:
      - loadbalancing
    depends_on:
      - backend

networks:
  loadbalancing:
